const constants = {
  SET_USER: "SET_USER",
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_USERS: "SET_USERS",
  SET_BASKET: "SET_BASKET",
  SET_SELECTED_TAB: "SET_SELECTED_TAB",
  CLEAR_BASKET: "CLEAR_BASKET",
  SET_ALL_PRODUCTS: "SET_ALL_PRODUCTS",
};
export default constants;
