name: Cypress Testing

on:
  push:
    branches:
      - main
    paths:
      - "react-testing/cypress-js/**"

jobs:
  e2e:
    name: "E2E Testing"
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
        working-directory: ./react-testing/cypress-js/
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress.io
        uses: cypress-io/github-action@v2.9.7
        with:
          start: yarn start

  component:
    name: "Component Testing"
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
        working-directory: ./react-testing/cypress-js/
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress.io
        uses: cypress-io/github-action@v2.9.7
        with:
          start: yarn start
