name: Cypress Tests with Dependency and Artifact Caching

on:
  push:
    branches:
      - main
    paths:
      - "react-testing/cypress-js/**"

jobs:
  cypress-run:
    name: "E2E Testing"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./react-testing/cypress-js
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Installing Dependencies"
        run: yarn

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
