name: Cypress Testing

on:
  push:
    branches:
      - main
    paths:
      - "react-testing/cypress-js/**"

jobs:
  e2e:
    name: "E2E Testing"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./react-testing/cypress-js/
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: "Installing Dependencies"
        run: yarn install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: yarn build
          start: yarn start
          component: false

  component:
    name: "Component Testing"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./react-testing/cypress-js/
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: "Installing Dependencies"
        run: yarn install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          component: true
          build: yarn build
          start: yarn start
